logging:
 level:
  root: INFO
  org.hibernate.SQL: DEBUG

spring:
 datasource:
  url: ${CONFERENCE_DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  generate-ddl: true
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    format_sql: true